### ISSUE TITLE
Method 'call' was called on null

### ISSUE THREAD

**Issue by Chimbi** [felixlucien/flutter-autocomplete-textfield#43]
This error let the Widget work but continues to appear on the log screen:
Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.

**Comment by onlinecheckwriter-zz** [comment]
add onFocusChanged: (hasFocus) {},
it should fix the problem

**Comment by felixmccuaig** [comment]
I'm going to need more information to be able to look into this, try including the code that was running at the time and output from the console.

**Comment by praharshbhatt** [comment]
I'm having the same issue.
I am populating the data from Cloud firestore, so am using a futurebuilder:

```
                //Search
                FutureBuilder(
                  builder: (BuildContext context, AsyncSnapshot snapshot) {
                    if (snapshot == null || snapshot.data == null || snapshot.hasData == false) {
                      return Center(
                        child: CircularProgressIndicator(
                          valueColor: AlwaysStoppedAnimation<Color>(Colors.green),
                          strokeWidth: 5,
                        ),
                      );
                    } else {
                      return Container(
                        color: Colors.white,
                        child: Padding(
                          padding: const EdgeInsets.fromLTRB(10, 10, 10, 0),
                          child: AutoCompleteTextField<CustomerList>(
                            decoration:
                            new InputDecoration(hintText: "Search Customers:", prefixIcon: new Icon(Icons.search)),
                            key: _searchKey,
                            onFocusChanged: (hasFocus) {},
                            suggestions: _lstCustomerList,
                            itemBuilder: (context, suggestion) =>
                                Padding(
                                    child: new ListTile(
                                        title: new Text(suggestion.strFirstName + " " + suggestion.strLastName),
                                        trailing: new Text("Phone: ${suggestion.strPhoneNumber}")),
                                    padding: EdgeInsets.all(8.0)),
                            itemSorter: (a, b) =>
                            0,
                            itemFilter: (suggestion, input) =>
                                suggestion.strFirstName.toLowerCase().startsWith(input.toLowerCase()),
                            itemSubmitted: (item) {
                              setState(() {
                                //Update the _selectedCustomer
                                _selectedCustomer = item;

                                //Update the Name and Phone number fields of the text fields
                                _tecName.text = _selectedCustomer.strFirstName;
                                _tecPhoneNumber.text = _selectedCustomer.strPhoneNumber;
                              });
                            },
                          ),
                        ),
                      );
                    }
                  },
                  future: getCustomerList(),
                ),
```

Error: 
```

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building CreateLinkScreen(dirty, dependencies: [MediaQuery], state: _CreateLinkScreenState#3469d):
The method '+' was called on null.
Receiver: null
Tried calling: +(" ")

════════════════════════════════════════════════════════════════════════════════════════════════════

```


The issue persists even after adding "onFocusChanged: (hasFocus) {},"
